// Package vmimport parses foreign VM descriptors (VMware OVA/OVF, Proxmox
// qemu-server .conf, Proxmox vzdump/.vma) into a neutral intermediate
// representation (ForeignVM) and maps it onto litevirt's VM spec + libvirt
// domain config. It is pure (no daemon/gRPC deps) so the adapters are
// unit-testable in isolation; the daemon handler drives conversion + define.
package vmimport

import (
	"fmt"

	pb "github.com/litevirt/litevirt/gen/litevirt/v1"
	lv "github.com/litevirt/litevirt/internal/libvirt"
)

// ForeignVM is the source-neutral representation an adapter produces. Disks are
// ordered with the boot disk first (index 0). Warnings are advisory notes for
// the operator (degraded fidelity, dropped devices) — never fatal.
type ForeignVM struct {
	Name       string
	GuestOS    string // informational hint (e.g. "windows", "linux")
	Machine    string // "q35" | "pc"
	Firmware   string // "uefi" | "bios"
	SecureBoot bool   // source had Secure Boot enabled → imported with Secure Boot (G1)
	HasTPM     bool   // source had a vTPM → imported with a FRESH vTPM (secret not carried; G1)
	CPUs       int
	MemoryMiB  int
	Disks      []ForeignDisk
	NICs       []ForeignNIC
	Warnings   []string
}

// ForeignDisk is one source disk. LocalPath starts as the staged/source file and
// is rewritten by the handler to the converted qcow2 path before ToVMConfig.
type ForeignDisk struct {
	Name            string // litevirt disk name ("root", "disk1", …)
	SourceID        string // source device key (Proxmox "scsi0", OVF diskId, VMA dev name) for --disk-map
	LocalPath       string // source file (pre-convert) → converted qcow2 (post-convert)
	Format          string // detected source format hint for qemu-img -f (vmdk|raw|qcow2|vpc|vdi)
	Bus             string // virtio | scsi | sata | ide
	ControllerModel string // SCSI controller model (virtio-scsi|lsisas1068|…); scsi only
	CapacityBytes   uint64 // declared virtual size (informational; authoritative size read post-convert)
	IsCDROM         bool   // CDROM/installer media — not converted, handled separately
}

// ForeignNIC is one source interface. Network holds the foreign network name
// (pre-mapping) and is rewritten by the handler to the resolved litevirt bridge.
type ForeignNIC struct {
	Network string // foreign network name → resolved bridge
	Model   string // virtio | e1000 | rtl8139
	MAC     string // source MAC ("" → generated by the handler)
	VLAN    int    // 802.1Q tag; 0 = untagged → VMSpec.network[].trunk
}

// Warnf appends a formatted advisory warning.
func (fv *ForeignVM) Warnf(format string, args ...interface{}) {
	fv.Warnings = append(fv.Warnings, fmt.Sprintf(format, args...))
}

// Normalize fills in safe defaults so a partially-populated ForeignVM maps
// deterministically. Adapters should set Machine/Firmware explicitly; this only
// guards against an empty value (xmlgen treats empty firmware as UEFI, which
// would silently mis-boot a BIOS guest, so default to bios here).
func (fv *ForeignVM) Normalize() {
	if fv.Machine == "" {
		fv.Machine = "q35"
	}
	if fv.Firmware == "" {
		fv.Firmware = "bios"
	}
	if fv.CPUs <= 0 {
		fv.CPUs = 1
	}
	if fv.MemoryMiB <= 0 {
		fv.MemoryMiB = 1024
	}
	for i := range fv.Disks {
		if fv.Disks[i].Bus == "" {
			fv.Disks[i].Bus = "virtio"
		}
		if fv.Disks[i].Name == "" {
			if i == 0 {
				fv.Disks[i].Name = "root"
			} else {
				fv.Disks[i].Name = fmt.Sprintf("disk%d", i)
			}
		}
	}
	for i := range fv.NICs {
		if fv.NICs[i].Model == "" {
			fv.NICs[i].Model = "virtio"
		}
	}
}

// dataDisks returns the non-CDROM disks (the ones that become VM disks).
func (fv *ForeignVM) dataDisks() []ForeignDisk {
	out := make([]ForeignDisk, 0, len(fv.Disks))
	for _, d := range fv.Disks {
		if !d.IsCDROM {
			out = append(out, d)
		}
	}
	return out
}

// ToVMConfig builds the libvirt domain config for XML generation. It assumes the
// handler has already rewritten disk LocalPaths to the converted qcow2 paths and
// NIC Networks to resolved bridges, and applied the MAC policy. Cloud-init is
// deliberately NOT set — an imported disk boots its installed OS as-is.
func (fv *ForeignVM) ToVMConfig() lv.VMConfig {
	cfg := lv.VMConfig{
		Name:       fv.Name,
		CPU:        fv.CPUs,
		MemoryMiB:  fv.MemoryMiB,
		Machine:    fv.Machine,
		Firmware:   fv.Firmware,
		SecureBoot: fv.SecureBoot,
		TPM:        fv.HasTPM,
		GuestAgent: false,
		EnableVNC:  true, // imported guests have a real console; expose it
		Boot:       "disk",
	}
	for _, d := range fv.dataDisks() {
		cfg.Disks = append(cfg.Disks, lv.DiskConfig{
			Name:            d.Name,
			Path:            d.LocalPath,
			Bus:             d.Bus,
			ControllerModel: d.ControllerModel,
		})
	}
	for _, n := range fv.NICs {
		cfg.Networks = append(cfg.Networks, lv.NetworkConfig{
			Bridge: n.Network,
			Model:  n.Model,
			MAC:    n.MAC,
		})
	}
	return cfg
}

// ToVMSpec builds the pb.VMSpec persisted as the VM's stored spec. Disk sizes are
// informational (the converted qcow2 is authoritative); the handler may overwrite
// them with the post-convert virtual size. VLANs ride in network[].trunk so they
// survive a stopped→started cycle (reapplied at StartVM).
func (fv *ForeignVM) ToVMSpec(project string) *pb.VMSpec {
	spec := &pb.VMSpec{
		Name:       fv.Name,
		Cpu:        int32(fv.CPUs),
		MemoryMib:  int32(fv.MemoryMiB),
		Machine:    fv.Machine,
		Firmware:   fv.Firmware,
		SecureBoot: fv.SecureBoot,
		Tpm:        fv.HasTPM,
		GuestAgent: false,
		Boot:       "disk",
		Project:    project,
	}
	for _, d := range fv.dataDisks() {
		size := ""
		if d.CapacityBytes > 0 {
			size = fmt.Sprintf("%dG", (d.CapacityBytes+(1<<30)-1)/(1<<30))
		}
		spec.Disks = append(spec.Disks, &pb.DiskSpec{
			Name:            d.Name,
			Size:            size,
			Bus:             d.Bus,
			ControllerModel: d.ControllerModel,
		})
	}
	for _, n := range fv.NICs {
		na := &pb.NetworkAttachment{
			Name:  n.Network,
			Model: n.Model,
			Mac:   n.MAC,
		}
		if n.VLAN > 0 {
			na.Trunk = []int32{int32(n.VLAN)}
		}
		spec.Network = append(spec.Network, na)
	}
	return spec
}
