#!/usr/bin/env bash
#
# Generate the Homebrew formula for a release and (optionally) push it to the
# tap repo.
#
# This is a *binary* formula: it downloads the prebuilt release tarball for the
# user's OS/arch (produced by build-release.sh) instead of compiling. It works
# on both macOS (Homebrew) and Linux (Homebrew on Linux):
#   - macOS -> darwin client binary   (manage a remote cluster)
#   - Linux -> full linux binary      (can also run `litevirt daemon`)
#
# The GitHub owner/repo for asset URLs and the tap repo are parameters, never
# hardcoded — this repo is mirrored under more than one org.
#
# Env:
#   VERSION    release tag, e.g. v1.2.0                     (required)
#   OUTDIR     dir with the tarballs + checksums.txt        (default: dist)
#   REPO       source repo "owner/name" for asset URLs      (default: $GITHUB_REPOSITORY, else git remote)
#   TAP_REPO   tap repo "owner/homebrew-litevirt"           (optional; push skipped if unset)
#   TAP_TOKEN  token with write access to TAP_REPO          (required only to push)
#
# With no TAP_REPO/TAP_TOKEN the formula is written to $OUTDIR/litevirt.rb and
# the push is skipped, so CI can build the artifact before a tap is configured.
set -euo pipefail

VERSION="${VERSION:?VERSION is required (e.g. v1.2.0)}"
OUTDIR="${OUTDIR:-dist}"

# Source repo for the release-asset download URLs.
REPO="${REPO:-${GITHUB_REPOSITORY:-}}"
if [[ -z "$REPO" ]]; then
  # Fall back to the origin remote: git@github.com:owner/name.git or https form.
  origin="$(git config --get remote.origin.url || true)"
  REPO="$(printf '%s\n' "$origin" | sed -E 's#(git@github.com:|https://github.com/)##; s#\.git$##')"
fi
[[ -n "$REPO" ]] || { echo "cannot determine source REPO (owner/name)" >&2; exit 1; }

# Homebrew's version field is bare (no leading v).
BREW_VERSION="${VERSION#v}"
BASE_URL="https://github.com/${REPO}/releases/download/${VERSION}"
CHECKSUMS="${OUTDIR}/litevirt-${VERSION}-checksums.txt"
[[ -f "$CHECKSUMS" ]] || { echo "missing checksums file: $CHECKSUMS" >&2; exit 1; }

# Look up the sha256 for one artifact out of the checksums file. sha256sum
# writes "<hash>  ./<file>"; match on the basename to ignore the ./ prefix.
sha_for() {
  local file="$1" hash
  hash="$(awk -v f="$file" '$2 ~ ("/" f "$") || $2 == f {print $1}' "$CHECKSUMS")"
  [[ -n "$hash" ]] || { echo "no sha256 for $file in $CHECKSUMS" >&2; exit 1; }
  printf '%s' "$hash"
}

tarball() { printf 'litevirt-%s-%s-%s.tar.gz' "$VERSION" "$1" "$2"; }

DARWIN_ARM="$(tarball darwin arm64)"
DARWIN_AMD="$(tarball darwin amd64)"
LINUX_ARM="$(tarball linux arm64)"
LINUX_AMD="$(tarball linux amd64)"

FORMULA="${OUTDIR}/litevirt.rb"
cat > "$FORMULA" <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/ci/brew-formula.sh — do not edit by hand.
class Litevirt < Formula
  desc "Masterless KVM/QEMU cluster orchestrator (macOS builds are CLI/UI client)"
  homepage "https://github.com/${REPO}"
  version "${BREW_VERSION}"
  license "GPL-2.0-only"

  on_macos do
    on_arm do
      url "${BASE_URL}/${DARWIN_ARM}"
      sha256 "$(sha_for "$DARWIN_ARM")"
    end
    on_intel do
      url "${BASE_URL}/${DARWIN_AMD}"
      sha256 "$(sha_for "$DARWIN_AMD")"
    end
  end

  on_linux do
    on_arm do
      url "${BASE_URL}/${LINUX_ARM}"
      sha256 "$(sha_for "$LINUX_ARM")"
    end
    on_intel do
      url "${BASE_URL}/${LINUX_AMD}"
      sha256 "$(sha_for "$LINUX_AMD")"
    end
  end

  def install
    bin.install "litevirt"
    bin.install_symlink "litevirt" => "lv"
  end

  def caveats
    <<~CAVEAT
      litevirt is one binary: \`litevirt daemon\` is the cluster host and
      \`litevirt <cmd>\` (alias \`lv\`) is the CLI/UI client.

      On macOS only the client works — hosting VMs needs Linux + KVM/QEMU.
      Point it at a remote cluster (creds in ~/.config/litevirt/pki):
        export LV_HOST=<host>   # gRPC/mTLS on :7443
        lv host list
    CAVEAT
  end

  test do
    assert_match "litevirt", shell_output("#{bin}/litevirt version")
  end
end
EOF

echo "wrote formula: $FORMULA"

# No tap configured -> stop after generating the file.
if [[ -z "${TAP_REPO:-}" ]]; then
  echo "TAP_REPO unset; skipping push (formula left in $FORMULA)"
  exit 0
fi
[[ -n "${TAP_TOKEN:-}" ]] || { echo "TAP_REPO set but TAP_TOKEN missing" >&2; exit 1; }

# Clone the tap, drop the formula under Formula/, commit, push.
workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT
git clone --depth 1 "https://x-access-token:${TAP_TOKEN}@github.com/${TAP_REPO}.git" "$workdir/tap"
mkdir -p "$workdir/tap/Formula"
cp "$FORMULA" "$workdir/tap/Formula/litevirt.rb"

git -C "$workdir/tap" config user.name "litevirt-release[bot]"
git -C "$workdir/tap" config user.email "litevirt-release@users.noreply.github.com"
git -C "$workdir/tap" add Formula/litevirt.rb
if git -C "$workdir/tap" diff --cached --quiet; then
  echo "formula unchanged; nothing to push"
  exit 0
fi
git -C "$workdir/tap" commit -m "litevirt ${VERSION}"
git -C "$workdir/tap" push origin HEAD
echo "pushed litevirt ${VERSION} to ${TAP_REPO}"
