package corrosion

import "strings"

// appendOnlyTables are immutable append-only tables: a replicated INSERT is applied with
// INSERT OR IGNORE and never LWW-gated, because a row never changes after creation.
var appendOnlyTables = map[string]bool{
	"fencing_log":  true,
	"audit_log":    true,
	"mutation_log": true,
	"vm_events":    true,
	// A chain head is a signed assertion about a fixed (host, epoch, seq); it
	// has no later revision. Append-only is what stops a replayed older head
	// from displacing a newer one on a peer, which is exactly the move that
	// would hide a truncation.
	"audit_chain_heads": true,
	// leader_lease_terms is deliberately NOT listed here. It is append-only in
	// spirit, but registering it as such made the WAL path (INSERT OR IGNORE,
	// first-writer-wins) and the anti-entropy path (LWW on updated_at,
	// last-writer-wins) resolve a contested (key, term) to DIFFERENT holders. It
	// is in customMergeTables instead, whose merge keeps the local row on both
	// paths and flags a genuine conflict; deriveDisposition checks
	// customMergeTables first, so an entry here would be unreachable anyway and
	// would only create a second, disagreeing source of truth.
	//
	// A retirement is a signed assertion about a fixed (host, key). It has no
	// later revision, and append-only is what makes it self-repairing: a row
	// deleted locally has nothing to conflict with, so anti-entropy re-inserts
	// it from a peer without any bespoke merge rule.
	"audit_key_lifecycle": true,
	// A CRL is a CA-signed assertion about a fixed revision number, so the row for
	// a given number has no later revision either. Append-only is what makes the
	// table safe to let any peer write to: a hostile row can only ever be a NEW
	// number, never a rewrite of the one carrying the revocation a reader wants.
	"cluster_crl": true,
}

// deriveDisposition classifies a parsed replicated statement into the disposition the apply
// path uses. It is the single source of truth for authorization: the compatibility ledger
// (stmtledger_generated.go) is generated by running it over every builder statement, so a
// fingerprint's ledger disposition and its derivation can never disagree. A statement it
// can't classify safely returns an error, which fails the CI guard (the shape must be made
// classifiable before it can ship).
func deriveDisposition(sh StmtShape) (Disposition, ConcurrencyCategory, error) {
	// Non-overridable structural invariant, defense-in-depth (LedgerEntryFor also checks it BEFORE any
	// explicit policy).
	if err := shapeInvariantError(sh); err != nil {
		return "", CatNone, err
	}
	t := sh.Table
	// Custom-merge tables (monotone lifecycle / immutable journal) merge by their own rule
	// regardless of statement kind.
	if customMergeTables[t] != nil {
		return DispCustomMerge, CatNone, nil
	}
	switch sh.Kind {
	case KindInsert:
		// append-only applies to INSERTs: never overwrite an existing immutable row.
		if appendOnlyTables[t] {
			return DispAppendOnly, CatNone, nil
		}
		if sh.OnConflict != nil {
			return DispExplicitUpsert, CatNone, nil
		}
		return DispPlainInsert, CatNone, nil
	case KindUpdate:
		if sh.HasFullPKIdentity {
			// A full-PK UPDATE is LWW-gated only when it binds updated_at (the clock the gate
			// compares).
			if sh.UpdatedAtParamIdx >= 0 {
				return DispFullPKUpdate, CatNone, nil
			}
			// A no-clock full-PK UPDATE (no bound updated_at) is NOT auto-derived: applying it
			// verbatim can regress a replicated timestamp when writes from different origins
			// arrive out of order (session/token last_used_at). It requires an EXPLICIT,
			// audited per-fingerprint policy (explicitPolicyDefs) that says whether it is
			// idempotent/terminal (apply verbatim) or a monotone-timestamp update (advance
			// only). LedgerEntryFor consults the explicit policy first; reaching here means a
			// no-clock shape has none, which fails the guard until one is added.
			return "", CatNone, invalidf("no-clock full-PK update on %s requires an explicit ledger policy", sh.Table)
		}
		// A bulk UPDATE (no full-PK identity) is applied by per-row LWW expansion, which is safe
		// ONLY when the statement binds updated_at (SET updated_at = ?) so each matched row can be
		// LWW-gated. A PK rekey is fine — the expansion re-keys each row scoped to its FULL prior PK
		// and back-pressures on a collision (see bulkUpdateIsPerRowLWWSafe). A bulk UPDATE with no
		// bound updated_at CANNOT be replicated safely, so it is NOT admitted to the ledger: return
		// an error (ledger GENERATION fails) rather than emitting a CatUnsupported entry into a
		// shipped ledger. The source builder must be rewritten row-scoped with a full PK + updated_at.
		if bulkUpdateIsPerRowLWWSafe(sh) {
			return DispBulkUpdate, CatPerRowLWW, nil
		}
		return "", CatNone, invalidf("bulk update on %s has no bound updated_at, so it cannot be per-row LWW-gated; rewrite the builder row-scoped with a full PK + updated_at", sh.Table)
	case KindDelete:
		// A DELETE reaches the ledger only when emitted by a known replicating builder, so
		// its presence IS the registration as a retention template.
		return DispDeleteRetention, CatNone, nil
	}
	return "", CatNone, invalidf("unclassifiable statement kind %s", sh.Kind)
}

// shapeInvariantError enforces NON-OVERRIDABLE structural invariants. It is checked BEFORE any
// explicit per-fingerprint policy AND inside deriveDisposition, so neither an explicit policy nor a
// hand-added ledger entry can authorize a shape that violates it. Currently: a builder on an identity
// table must not bind/assign a self-reference column (identityReferenceColumns, e.g.
// snapshots.parent_id), because the identity collapse fails closed on such references rather than
// rewriting them — a writer that set one would silently invalidate that assumption.
func shapeInvariantError(sh StmtShape) error {
	for _, ref := range identityReferenceColumns[sh.Table] {
		if shapeBindsColumn(sh, ref) {
			return invalidf("builder on identity table %s binds reference column %q: H1 identity collapse fails closed on references and does NOT rewrite them — add reference rewriting to the collapse/apply paths before any writer sets %q", sh.Table, ref, ref)
		}
	}
	return nil
}

// shapeBindsColumn reports whether the statement writes the named column — as an INSERT column or an
// UPDATE SET target (case-insensitive, matching the parser's identifier normalization).
func shapeBindsColumn(sh StmtShape, col string) bool {
	for _, c := range sh.InsertCols {
		if strings.EqualFold(c, col) {
			return true
		}
	}
	for _, a := range sh.SetAssigns {
		if strings.EqualFold(a.Column, col) {
			return true
		}
	}
	return false
}

// bulkUpdateIsPerRowLWWSafe reports whether a bulk (non-full-PK) UPDATE can be applied by
// per-row LWW expansion: it must assign updated_at (the incoming clock each matched row is
// gated by). A rekey of a primary-key column is still safe — the expansion enumerates by the
// original predicate and applies each row scoped to its FULL prior PK, so it becomes a
// row-scoped rekey that simply back-pressures (fails closed) if the new key collides with an
// existing row.
func bulkUpdateIsPerRowLWWSafe(sh StmtShape) bool {
	return sh.UpdatedAtParamIdx >= 0
}

// explicitPolicyDef is an audited, hand-maintained disposition for a specific statement whose
// safe handling can NOT be auto-derived — currently the no-clock full-PK updates. Each names
// its exact statement and, for a monotonic-timestamp update, the column the receiver must only
// ADVANCE (never regress on an out-of-order write). Idempotent/terminal updates leave
// MonotoneColumn empty and apply verbatim.
type explicitPolicyDef struct {
	SQL            string
	Disposition    Disposition
	MonotoneColumn string
	// RequiresCapability/DispositionAfter make a shape CAPABILITY-GATED (Part H): before the
	// capability is active on the receiver, Disposition applies (use DispReject to fail closed);
	// once active, DispositionAfter applies. Empty ⇒ an ungated policy.
	RequiresCapability string
	DispositionAfter   Disposition
}

var explicitPolicyDefs = []explicitPolicyDef{
	// Create-begin resurrection is ordered by its strictly increasing
	// owner_epoch + spec_generation predicate, not by unrelated node clocks.
	// The receiver additionally requires workload_create_begin_v1 before the
	// exact statement is applied.
	{SQL: vmCreateBeginSQL, Disposition: DispCreateBegin},
	{SQL: containerCreateBeginSQL, Disposition: DispCreateBegin},
	// The terminal workload transition is the commit barrier for the preceding
	// hardware/journal statements in the same mutation-log transaction. Its
	// structured authority guard, not an unrelated receiver clock, orders it.
	{SQL: vmCreateCommitSQL, Disposition: DispGuardedTransition},
	{SQL: vmCreateRollbackSQL, Disposition: DispGuardedTransition},
	{SQL: containerCreateCommitSQL, Disposition: DispGuardedTransition},
	{SQL: containerCreateRollbackSQL, Disposition: DispGuardedTransition},
	{SQL: vmDeleteSQL, Disposition: DispWorkloadDelete},
	{SQL: containerDeleteSQL, Disposition: DispWorkloadDelete},
	// Pre-v44 deletes carry no authority axes. Retain wire compatibility, but
	// only let them tombstone rows that are themselves still pre-authority.
	{SQL: legacyVMDeleteSQL, Disposition: DispLegacyWorkloadDelete},
	{SQL: legacyContainerDeleteSQL, Disposition: DispLegacyWorkloadDelete},
	{SQL: legacyContainerStrictDeleteSQL, Disposition: DispLegacyWorkloadDelete},
	// audit_log hash-chain reseal: idempotent (recomputes the same hashes), and
	// applied through the signature-guarded form on the receiver.
	//
	// BOTH shapes carry DispAuditReseal, which is what makes the pre-v45 one
	// safe. That shape has no signature predicate; applied verbatim it would let
	// a node that rewrote its own signed rows emit the old form and have every
	// peer overwrite its good content_hash by primary key, with no clock compare
	// and no recovery — reseal refuses to touch signed rows, so the correct hash
	// could never be restored. The disposition rewrites it to the guarded form
	// on arrival, so a legacy sender keeps working (its rows carry no signature,
	// which is everything the guard could ever exclude) while a signed row is
	// unreachable by any reseal, local or replicated.
	{SQL: auditResealGuardedSQL, Disposition: DispAuditReseal},
	// Pre-v45 shape, retained for the upgrade horizon (stmthistorical.go).
	{SQL: `UPDATE audit_log SET prev_hash = ?, content_hash = ? WHERE id = ?`, Disposition: DispAuditReseal},
	// session revoke: a guarded one-shot terminal transition (WHERE revoked_at IS NULL) → verbatim.
	{SQL: `UPDATE sessions SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL`, Disposition: DispFullPKUpdateNoClock},
	// session touch: last_used_at must only advance (align with AE's timestamp-max merge).
	{SQL: `UPDATE sessions SET last_used_at = ? WHERE id = ? AND revoked_at IS NULL`, Disposition: DispFullPKUpdateNoClock, MonotoneColumn: "last_used_at"},
	// token touch: last_used_at must only advance.
	{SQL: `UPDATE tokens SET last_used_at = ? WHERE id = ?`, Disposition: DispFullPKUpdateNoClock, MonotoneColumn: "last_used_at"},
	// Canonical registry-credential upsert (Part H2): REJECT until canonical_registry_v1 is active
	// on this receiver (so a prematurely-enabled peer can't inject canonical rows while legacy
	// writers still run), then apply through DispCanonicalRegistry, which verifies the
	// deterministic-ID contract before the LWW upsert. (The legacy mint-new-id INSERT is NOT
	// capability-gated — it auto-derives to DispPlainInsert and stays accepted; rejecting it is part
	// of the deferred operator-run writer-activation contract, not this reversible core.)
	{SQL: registryCanonicalUpsertSQL, Disposition: DispReject, RequiresCapability: capCanonicalRegistryV1, DispositionAfter: DispCanonicalRegistry},
}

var explicitPolicyByFP = buildExplicitPolicies()

func buildExplicitPolicies() map[string]LedgerEntry {
	m := make(map[string]LedgerEntry, len(explicitPolicyDefs))
	for _, d := range explicitPolicyDefs {
		fp, err := FingerprintSQL(d.SQL)
		if err != nil {
			panic("explicit policy SQL does not parse: " + d.SQL + ": " + err.Error())
		}
		m[fp] = LedgerEntry{
			Disposition:        d.Disposition,
			MonotoneColumn:     d.MonotoneColumn,
			RequiresCapability: d.RequiresCapability,
			DispositionAfter:   d.DispositionAfter,
		}
	}
	return m
}

// explicitPolicy returns the audited per-fingerprint policy, if one is registered.
func explicitPolicy(fp string) (LedgerEntry, bool) {
	e, ok := explicitPolicyByFP[fp]
	return e, ok
}

// LedgerEntryFor derives the compatibility-ledger entry for one replicated builder statement.
// The CI guard's -emit-ledger mode calls it to generate stmtledger_generated.go. An explicit,
// audited per-fingerprint policy (explicitPolicyDefs) overrides DERIVATION — but NOT the
// non-overridable structural invariants (shapeInvariantError), which are checked first so a policy
// can never authorize a forbidden shape (e.g. a snapshots.parent_id writer).
func LedgerEntryFor(sql string) (LedgerEntry, error) {
	// Table + PK metadata from the structural parse (parseResolved), never the comment-sensitive
	// string scan — so a builder's fingerprint is always paired with its OWN table's PKs.
	sh, _, err := parseResolved(sql)
	if err != nil {
		return LedgerEntry{}, err
	}
	// Non-overridable invariants BEFORE the explicit-policy lookup.
	if err := shapeInvariantError(sh); err != nil {
		return LedgerEntry{}, err
	}
	fp := stmtFingerprint(sh)
	if e, ok := explicitPolicy(fp); ok {
		e.Fingerprint, e.Kind, e.Table = fp, sh.Kind.String(), sh.Table
		return e, nil
	}
	disp, cat, err := deriveDisposition(sh)
	if err != nil {
		return LedgerEntry{}, err
	}
	return LedgerEntry{Fingerprint: fp, Kind: sh.Kind.String(), Table: sh.Table, Disposition: disp, Category: cat}, nil
}
